### ISSUE TITLE
Cannot include Locale in a built value

### ISSUE THREAD

**Issue by kentcb** [google/built_value.dart#661]
When attempting to include a `Locale` in a built value, the generator fails with:

```
[SEVERE] built_value_generator:built_value on lib/repro.dart:
Error in BuiltValueGenerator for abstract class ReproDto implements Built<ReproDto, dynamic>.
Please make the following changes to use BuiltValue:

1. Make field bar have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
```

Here is the repro code:

```dart
import 'dart:ui';

import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'repro.g.dart';

abstract class ReproDto implements Built<ReproDto, ReproDtoBuilder> {
  factory ReproDto([void Function(ReproDtoBuilder) updates]) = _$ReproDto;

  ReproDto._();

  static Serializer<ReproDto> get serializer => _$reproDtoSerializer;

  String get foo;
  Locale get bar;
}
```

As you can see, the `Locale` type is correctly imported from `dart:ui`. If I comment out the `bar` property then it generates fine, but as soon as I try to include the `Locale` object, it fails with the above error.

**Comment by davidmorgan** [comment]
I think this is the same as #282 which should now be solved in `package:build` itself--please reopen if not.

**Comment by kentcb** [comment]
@davidmorgan I'd like this reopened please, as I'm still getting it with `build` `1.2.2`

**Comment by davidmorgan** [comment]
Could you please ask at

https://github.com/dart-lang/build/issues/733

? That's the underlying issue. Thanks.

**Comment by kentcb** [comment]
Ah, looks like I just had to clean out `.dart_tool/build_resolvers` for it to work. Thanks @davidmorgan

**Comment by dave26199** [comment]
Thanks @kentcb :)
